import random

#id, nombre, laboratorio, precio en soles, unidad por blister, stock

def generar_tuplas(n):
    nombre  = [
    "Paracetamol",
    "Ibuprofeno",
    "Amoxicilina",
    "Omeprazol",
    "Metformina",
    "Atorvastatina",
    "Simvastatina",
    "Pantoprazol",
    "Lorazepam",
    "Ciprofloxacino",
    "Diazepam",
    "Clonazepam",
    "Lisinopril",
    "Losartan",
    "Sertralina",
    "Escitalopram",
    "Fluoxetina",
    "Metronidazol",
    "Clindamicina",
    "Azitromicina",
    "Diclofenaco",
    "Naproxeno",
    "Tramadol",
    "Cetirizina",
    "Levotiroxina",
    "Furosemida",
    "Salbutamol",
    "Hidroclorotiazida",
    "Metoprolol",
    "Enalapril",
    "Warfarina",
    "Amlodipino",
    "Fenitoina",
    "Carbamazepina",
    "Risperidona",
    "Metoclopramida",
    "Amitriptilina",
    "Pregabalina",
    "Insulina",
    "Rosuvastatina",
    "Citalopram",
    "Venlafaxina",
    "Mirtazapina",
    "Duloxetina",
    "Levetiracetam",
    "Lansoprazol",
    "Ranitidina",
    "Piroxicam",
    "Indometacina",
    "Dexametasona",
    "Prednisona",
    "Clotrimazol",
    "Fluconazol",
    "Esomeprazol",
    "Vitamina C",
    "Vitamina D",
    "Vitamina B12",
    "Calcio",
    "Hierro",
    "Magnesio",
    "Potasio",
    "Acetaminofen",
    "Cefalexina",
    "Cloranfenicol",
    "Fenilefrina",
    "Hidrocortisona",
    "Levofloxacino",
    "Paroxetina",
    "Rabeprazol",
    "Doxorrubicina",
    "Metildopa",
    "Propranolol",
    "Alprazolam",
    "Oxcarbazepina",
    "Tacrolimus",
    "Clobetasol",
    "Nistatina",
    "Metamizol",
    "Hidroxicloroquina",
    "Sulfametoxazol",
    "Trimetoprima",
    "Tamsulosina",
    "Tadalafil",
    "Sildenafil",
    "Amiodarona",
    "Fenofibrato",
    "Prazosina",
    "Lamotrigina",
    "Allopurinol",
    "Meloxicam",
    "Morfina",
    "Oxicodona",
    "Doxazosina",
    "Quetiapina",
    "Clopidogrel",
    "Ciclosporina",
    "Tacrina",
    "Terbinafina",
    "Itraconazol",
    "Pantoprazol",
    "Eritromicina",
    "Levotiroxina",
    "Levocetirizina",
    "Dipirona",
    "Dexketoprofeno",
    "Aciclovir",
    "Metamizol",
    "Betametasona",
    "Prednisona",
    "Clobetasol",
    "Salbutamol",
    "Mometasona",
    "Ondansetron",
    "Loperamida",
    "Clotrimazol",
    "Fexofenadina",
    "Montelukast",
    "Pseudoefedrina",
    "Alendronato",
    "Ranitidina",
    "Bromuro de Otilonio",
    "Loperamida",
    "Nistatina",
    "Amoxicilina",
    "Azitromicina",
    "Metronidazol",
    "Doxiciclina",
    "Sulfametoxazol",
    "Trimetoprima",
    "Cefuroxima",
    "Cefixima",
    "Ciprofloxacino",
    "Fluconazol",
    "Ebastina",
    "Tenofovir",
    "Darunavir",
    "Raltegravir",
    "Efavirenz",
    "Lamivudina",
    "Lopinavir",
    "Ritonavir",
    "Nevirapina",
    "Ibuprofeno",
    "Naproxeno",
    "Diclofenaco",
    "Ketorolaco",
    "Dipirona",
    "Hidroxicloroquina",
    "Oseltamivir",
    "Permetrina",
    "Benznidazol",
    "Nifedipino",
    "Amlodipino",
    "Losartan",
    "Hidroclorotiazida",
    "Carvedilol",
    "Digoxina",
    "Furosemida",
    "Spironolactona",
    "Metoprolol",
    "Atenolol",
    "Isosorbide",
    "Nitroglicerina",
    "Insulina",
    "Metformina",
    "Glibenclamida",
    "Pioglitazona",
    "Sitagliptina",
    "Vildagliptina",
    "Rosiglitazona",
    "Ezetimiba",
    "Lovastatina",
    "Pravastatina",
    "Aspirina",
    "Clopidogrel",
    "Warfarina",
    "Dabigatran",
    "Enoxaparina",
    "Rivaroxaban",
    "Levetiracetam",
    "Lamotrigina",
    "Valproato",
    "Fenitoina",
    "Olanzapina",
    "Quetiapina",
    "Risperidona",
    "Clozapina",
    "Alprazolam",
    "Clonazepam",
    "Lorazepam",
    "Diazepam",
    "Oxazepam",
    "Flurazepam",
    "Paroxetina",
    "Sertralina",
    "Fluoxetina",
    "Citalopram",
    "Escitalopram",
    "Venlafaxina",
    "Mirtazapina",
    "Duloxetina"
]

    laboratorios = [
    "Pfizer",
    "Johnson & Johnson",
    "Novartis",
    "Roche",
    "Merck & Co.",
    "GlaxoSmithKline",
    "Sanofi",
    "AbbVie",
    "AstraZeneca",
    "Bayer",
    "Gilead Sciences",
    "Eli Lilly and Company",
    "Amgen",
    "Bristol-Myers Squibb",
    "Takeda Pharmaceutical",
    "Novo Nordisk",
    "Boehringer Ingelheim",
    "Biogen",
    "Stryker",
    "Celgene",
    "Abbott Laboratories",
    "Allergan",
    "Mylan",
    "Mitsubishi Tanabe Pharma",
    "Alexion Pharmaceuticals",
    "Shire",
    "Teva Pharmaceutical Industries",
    "Daiichi Sankyo",
    "Becton, Dickinson and Company",
    "Vertex Pharmaceuticals",
    "Grifols",
    "Fresenius Medical Care",
    "Otsuka Pharmaceutical",
    "Regeneron Pharmaceuticals",
    "Hoffmann-La Roche",
    "Cephalon",
    "Astellas Pharma",
    "Mylan",
    "Kyowa Hakko Kirin",
    "Daiichi Sankyo",
    "Lundbeck",
    "Mitsubishi Tanabe Pharma",
    "Santen Pharmaceutical",
    "Sumitomo Dainippon Pharma",
    "Aspen Pharmacare",
    "Cipla",
    "Sun Pharmaceutical",
    "Dr. Reddy's Laboratories",
    "Hikma Pharmaceuticals",
    "Mundipharma",
    "Taro Pharmaceuticals",
    "Boehringer Ingelheim",
    "Hospira",
    "Mylan",
    "Sandoz",
    "Actavis",
    "Teva Pharmaceutical Industries",
    "Ranbaxy Laboratories",
    "Cipla",
    "Apotex",
    "Mylan",
    "Perrigo",
    "Fresenius Kabi",
    "Abbott Laboratories",
    "Piramal Enterprises",
    "Torrent Pharmaceuticals",
    "Takeda Pharmaceutical",
    "Sun Pharmaceutical",
    "Lupin",
    "Zydus Cadila",
    "Glenmark Pharmaceuticals",
    "Gilead Sciences",
    "Biogen",
    "Regeneron Pharmaceuticals",
    "Vertex Pharmaceuticals",
    "Alexion Pharmaceuticals",
    "Celgene",
    "Bristol-Myers Squibb",
    "Amgen",
    "Eli Lilly and Company",
    "Merck KGaA",
    "Grifols",
    "Novo Nordisk",
    "Sanofi",
    "GlaxoSmithKline",
    "Bayer",
    "AstraZeneca",
    "AbbVie",
    "Roche",
    "Merck & Co.",
    "Novartis",
    "Johnson & Johnson",
    "Pfizer"
    ]

    nombre = list(set(nombre))
    laboratorios = list(set(laboratorios))
    tuplas = []
    


    for i in range(n):
        id = random.randint(1000, 9999)
        while True:
            nombres = random.choice(nombre)
            if nombres not in [t[1] for t in tuplas]:
                break
        laboratorio = random.choice(laboratorios)
        stock = random.randint(1, 100)
        precio = round(random.uniform(10.0, 1000.0), 2)
        unidad = random.randint(10,30)
        tupla = (id, nombres, laboratorio, precio, unidad, stock)
        tuplas.append(tupla) 
    return tuplas


tuplas_generadas = generar_tuplas(150)

with open("tablas_tuplas/medicamentos/medicamentos.csv", "w") as archivo:
    for tupla in tuplas_generadas:
        id, nombres, laboratorio, precio, unidad, stock = tupla
        linea = f"{id},{nombres},{laboratorio},{precio},{unidad},{stock}\n"
        archivo.write(linea)

print("Archivo generado exitosamente")
